name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy
          pip install -r requirements.txt
      
      - name: Run Ruff (linting)
        run: ruff check . --output-format=github
        continue-on-error: true
      
      - name: Run Black (formatting check)
        run: black --check --diff .
        continue-on-error: true
      
      - name: Run MyPy (type checking)
        run: |
          mypy crypto_portfolio_mcp.py additional_tools.py --ignore-missing-imports
        continue-on-error: true

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pip-audit
      
      - name: Run Bandit (security linting)
        run: bandit -r . -x ./tests,./venv --severity-level medium
        continue-on-error: true
      
      - name: Run pip-audit (dependency vulnerabilities)
        run: |
          pip install -r requirements.txt
          pip-audit
        continue-on-error: true
