#!/usr/bin/env python3
"""
Generate Part 5: FINAL expansion to exceed 350 total terms
Community Development & Miscellaneous (18 terms)
"""

import json

# Part 5: Final 18 terms to exceed 350 total
new_terms = [
    # === COMMUNITY DEVELOPMENT (18 terms) ===
    {
        "term": "Community Development",
        "definition": "Efforts to improve the economic, social, and environmental conditions of specific neighborhoods through resident-led initiatives, nonprofit organizations, and government programs. Community development emphasizes local control, building community capacity, addressing root causes of poverty and disinvestment, and empowering residents to shape their neighborhoods' futures. Effective community development combines physical improvements (housing, infrastructure) with human development (jobs, education, health).",
        "category": "Community Development",
        "louisville_context": "Louisville has numerous community development efforts, primarily led by nonprofit organizations like Louisville Central Community Centers, Center for Neighborhoods, and various Community Development Corporations (CDCs). West Louisville has faced decades of disinvestment requiring intensive community development. However, development often happens TO communities rather than WITH communities—outside entities making decisions without meaningful resident input or control.",
        "why_it_matters": "Top-down development imposed on communities often fails or creates gentrification and displacement rather than community empowerment. Successful community development requires genuine resident leadership, long-term commitment, comprehensive approaches addressing multiple challenges simultaneously, and ensuring development benefits existing residents rather than displacing them.",
        "related_terms": "Community Development Corporation, Neighborhood Revitalization, Community Organizing, Equitable Development, Resident Leadership",
        "dave_proposal": "Dave's Community Wellness Centers exemplify community development: resident-led governance, comprehensive services, local hiring, and community building. He'll significantly expand support for community development corporations and grassroots organizations, require genuine community engagement for all development projects, and ensure Louisville Metro investments support rather than supplant community-led development.",
        "aliases": "Neighborhood Development, Community Improvement, Local Development"
    },
    {
        "term": "Community Development Corporation (CDC)",
        "definition": "Nonprofit organizations focused on revitalizing specific geographic communities (typically low-income neighborhoods) through affordable housing development, economic development, community organizing, and social services. CDCs are governed by resident-majority boards, ensuring community control. CDCs build and manage affordable housing, support small businesses, provide job training, organize residents, and advocate for community needs. Strong CDCs are essential infrastructure in disinvested neighborhoods.",
        "category": "Community Development",
        "louisville_context": "Louisville has several CDCs including Americana Community Center (South End), Portland Promise Center (Portland neighborhood), Park DuValle CDC (Park DuValle neighborhood), and others serving specific communities. However, Louisville's CDCs are chronically underfunded compared to peer cities and can't meet the scale of need in West Louisville. Limited local foundation support and competitive government funding force CDCs to focus on projects that attract funding rather than greatest community need.",
        "why_it_matters": "CDCs provide resident-controlled organizations advocating for and serving disinvested neighborhoods. Without strong CDCs, communities lack organizational capacity to pursue development opportunities, resist harmful projects, or hold government accountable. Strengthening CDCs is essential for equitable development and community empowerment in West Louisville and other underserved areas.",
        "related_terms": "Community Development, Affordable Housing, Community Organizing, Nonprofit Organizations, Grassroots Leadership",
        "dave_proposal": "Dave will significantly increase Metro Government support for Louisville CDCs through multi-year operating grants allowing sustained staffing and planning (funded within $1.025 billion budget). He'll partner with CDCs on Community Wellness Centers, affordable housing, and economic development. He'll require city-funded development projects to meaningfully engage and support local CDCs as partners.",
        "aliases": "CDC, Neighborhood CDC, Community-Based Development Organization"
    },
    {
        "term": "Community Organizing",
        "definition": "Bringing neighbors together to identify shared concerns, build collective power, and take action to improve their community. Community organizing empowers residents to advocate for themselves rather than relying on outside saviors. Organizing involves leadership development, collective decision-making, confronting power structures, and building sustained organizations. Effective organizing changes both external conditions (winning improvements) and internal capacity (residents gaining skills, confidence, relationships).",
        "category": "Community Development",
        "louisville_context": "Louisville has rich community organizing history including civil rights organizing, environmental justice campaigns (Rubbertown), and tenant organizing. Current organizing groups include Kentuckians For The Commonwealth (KFTC), Louisville Showing Up for Racial Justice (LSURJ), and various neighborhood associations. However, organizing capacity is concentrated in certain neighborhoods while others lack organized resident power, limiting their ability to demand equitable treatment.",
        "why_it_matters": "Without organized resident power, low-income communities and communities of color remain politically invisible, allowing government and developers to ignore community needs or impose harmful projects. Community organizing builds democratic power enabling residents to hold government accountable, resist displacement, and shape neighborhood development. Organized communities get better services, more equitable treatment, and greater voice in decisions affecting their lives.",
        "related_terms": "Community Development, Grassroots Organizing, Resident Leadership, Power Building, Advocacy",
        "dave_proposal": "Dave will support community organizing by ensuring all Metro decisions affecting neighborhoods include genuine resident engagement, providing meeting spaces at Community Wellness Centers and community centers for organizing, protecting residents' right to organize without retaliation, and responding to organized community demands. He'll support organizations building resident power in underorganized neighborhoods.",
        "aliases": "Grassroots Organizing, Neighborhood Organizing, Resident Organizing, Base Building"
    },
    {
        "term": "Community Benefits Agreement (CBA)",
        "definition": "A legally binding contract between developers and community organizations ensuring development projects provide specific benefits to the community (jobs, affordable housing, community facilities, environmental protections, etc.). CBAs give communities enforcement power beyond vague developer promises. Common CBA provisions include local hiring percentages, living wage requirements, affordable housing units, open space, community facility space, and environmental standards. CBAs shift power toward communities in development negotiations.",
        "category": "Community Development",
        "louisville_context": "Louisville has rarely used Community Benefits Agreements despite major development projects receiving significant public subsidies. Downtown developments, data centers, and other projects receiving tax abatements typically make no enforceable commitments to community benefits. This allows developers to capture public subsidies while providing minimal community benefit. The lack of CBAs reflects low-income communities' limited organizing capacity and government's failure to require community benefits in exchange for public support.",
        "why_it_matters": "When Louisville provides millions in tax abatements and infrastructure for development projects without requiring enforceable community benefits, public resources subsidize private profit without public benefit. CBAs ensure development serves community needs, creates accessible jobs, and includes affordable housing. Without CBAs, development often causes displacement and inequality rather than shared prosperity.",
        "related_terms": "Economic Development Incentives, Community Development, Equitable Development, Community Organizing, Development Agreements",
        "dave_proposal": "Dave will require Community Benefits Agreements for all development projects receiving public subsidies over $500,000. CBAs will mandate local hiring percentages, living wage jobs, affordable housing inclusion, community facility space, and environmental standards. Community Wellness Centers will support neighborhood organizing to negotiate strong CBAs. He'll ensure CBAs are enforceable with real penalties for non-compliance.",
        "aliases": "CBA, Development Agreement, Community Benefit Compact"
    },
    {
        "term": "Equitable Development",
        "definition": "Development that provides benefits to all residents, particularly low-income residents and communities of color, without causing displacement. Equitable development includes affordable housing, living wage jobs accessible to existing residents, community-desired amenities (groceries, parks, transit), and community control over development decisions. Equitable development prevents gentrification by ensuring development strengthens rather than displaces existing communities.",
        "category": "Community Development",
        "louisville_context": "Most Louisville development has been inequitable: downtown and East End development benefits affluent residents while creating service jobs inaccessible to West Louisville residents lacking transportation. When development comes to low-income neighborhoods (Russell neighborhood's recent development), it often causes rising rents forcing long-time residents out. Louisville lacks policies ensuring development benefits existing residents: no inclusionary zoning, weak affordability requirements, no anti-displacement protections.",
        "why_it_matters": "Development that displaces existing residents through rising costs is neighborhood theft, not neighborhood improvement. When low-income communities finally see investment after decades of neglect, that investment must benefit long-time residents, not replace them with wealthier newcomers. Equitable development requires deliberate policies preventing displacement and ensuring community benefits.",
        "related_terms": "Gentrification, Anti-Displacement, Affordable Housing, Community Benefits Agreement, Development Justice",
        "dave_proposal": "Dave will make equitable development Louisville's standard through inclusionary zoning requiring affordable units, Community Benefits Agreements ensuring local jobs, anti-displacement programs (property tax relief, rental assistance) in gentrifying areas, community land trusts preventing speculation, and prioritizing community-desired development. All city-subsidized development will be evaluated for equitable outcomes within $1.025 billion budget.",
        "aliases": "Fair Development, Inclusive Development, Anti-Displacement Development"
    },
    {
        "term": "Gentrification",
        "definition": "The transformation of low-income neighborhoods through influx of wealthier residents, businesses, and development, increasing property values and costs while displacing long-time residents who can no longer afford to stay. Gentrification often follows decades of disinvestment in communities of color, with improvement benefiting newcomers rather than existing residents. Gentrification destroys communities, severs social networks, and perpetuates racial and economic inequality through displacement.",
        "category": "Community Development",
        "louisville_context": "Louisville is experiencing early-stage gentrification in Russell, Portland, and Smoketown neighborhoods as investors purchase properties anticipating future value increases. Downtown development and new amenities make adjacent neighborhoods attractive to higher-income residents. Long-time Black residents face rising rents and property taxes while seeing minimal benefit from development. Without anti-displacement policies, gentrification will accelerate as West Louisville becomes 'discovered' by investors and developers.",
        "why_it_matters": "Gentrification is often portrayed as neighborhood improvement, but it's actually neighborhood theft—replacing existing residents with wealthier ones. When Black communities that survived redlining, urban renewal, and decades of disinvestment finally see investment, they deserve to benefit rather than be displaced. Gentrification destroys communities, severs social ties, and perpetuates racial injustice through displacement disguised as development.",
        "related_terms": "Displacement, Equitable Development, Anti-Displacement, Affordable Housing, Community Development",
        "dave_proposal": "Dave will implement aggressive anti-displacement policies in gentrifying neighborhoods: property tax relief for long-time homeowners, rental assistance preventing displacement, enforcement against landlords forcing out tenants, community land trusts removing properties from speculative markets, inclusionary zoning ensuring affordable housing, and Community Benefits Agreements requiring local hiring. Policies funded within $1.025 billion budget.",
        "aliases": "Neighborhood Gentrification, Urban Displacement, Community Displacement"
    },
    {
        "term": "Anti-Displacement",
        "definition": "Policies and programs preventing existing residents from being forced out of their neighborhoods by rising rents, property taxes, or other costs resulting from development or gentrification. Anti-displacement strategies include rent control, just cause eviction protections, property tax relief for long-time homeowners, affordable housing preservation, community land trusts, tenant right-to-purchase, and legal protections against landlord harassment. Anti-displacement requires proactive intervention before displacement occurs.",
        "category": "Community Development",
        "louisville_context": "Louisville lacks comprehensive anti-displacement policies despite emerging gentrification in West Louisville neighborhoods. Kentucky state law prohibits rent control, limiting Louisville's anti-displacement tools. Current property tax relief programs reach few eligible residents. No tenant protections exist beyond state minimum landlord-tenant law. No right-to-return programs exist for residents displaced by development. This policy vacuum allows displacement to occur unchecked.",
        "why_it_matters": "Waiting until displacement occurs to address it is too late—displaced residents rarely return. Anti-displacement requires proactive policies implemented before gentrification accelerates. Without anti-displacement protections, West Louisville's coming development will repeat urban renewal's displacement of Black residents, destroying communities under the guise of improvement. Preventing displacement is a moral imperative and political necessity.",
        "related_terms": "Gentrification, Equitable Development, Tenant Protections, Affordable Housing, Displacement Prevention",
        "dave_proposal": "Dave will implement comprehensive anti-displacement strategy within his $1.025 billion budget: property tax freeze for long-time low-income homeowners in gentrifying areas ($5 million annually), rental assistance preventing displacement ($10 million annually), enhanced code enforcement against landlord harassment, expanded legal aid for tenant protections, and community land trusts acquiring properties. He'll track displacement indicators and intervene early.",
        "aliases": "Displacement Prevention, Gentrification Prevention, Tenant Protections"
    },
    {
        "term": "Community Land Trust (CLT)",
        "definition": "A nonprofit organization that owns land permanently, leasing it to homeowners or developers under long-term renewable ground leases with resale restrictions ensuring permanent affordability. Homeowners own buildings but lease land from the trust, making homes affordable in perpetuity rather than temporary affordability. CLTs prevent speculation, enable homeownership for low-income families, and ensure development benefits communities rather than investors. CLTs are powerful anti-displacement and community wealth-building tools.",
        "category": "Community Development",
        "louisville_context": "Louisville currently has no significant community land trust despite CLTs' success in peer cities. Habitat for Humanity operates limited CLT-like programs, but at small scale. West Louisville's rising property values make CLT development increasingly urgent—acquiring land now before prices escalate. CLTs could enable permanent affordability, prevent speculation, and ensure West Louisville development benefits existing residents rather than displacing them.",
        "why_it_matters": "Traditional affordable housing loses affordability when owners sell at market rates. CLTs maintain permanent affordability while enabling homeownership and wealth building for low-income families. In gentrifying neighborhoods, CLTs prevent speculation by removing land from market. CLTs also provide community control over development, ensuring it serves resident needs rather than investor profit.",
        "related_terms": "Affordable Housing, Anti-Displacement, Community Development, Equitable Development, Permanent Affordability",
        "dave_proposal": "Dave will establish Louisville Community Land Trust with $10 million seed funding within his $1.025 billion budget. The CLT will acquire properties in gentrifying West Louisville neighborhoods, develop permanently affordable housing (homes and rentals), and prevent speculation. Community Wellness Centers will help residents access CLT housing and participate in CLT governance. Priority acquisition in Russell, Portland, Smoketown neighborhoods facing gentrification pressure.",
        "aliases": "CLT, Land Trust, Community-Controlled Land, Permanent Affordability"
    },
    {
        "term": "Community Wealth Building",
        "definition": "Economic development strategies that build assets and ownership in communities rather than extracting wealth to distant shareholders. Community wealth building includes worker cooperatives, community land trusts, local businesses, community development financial institutions, and employee ownership. This approach keeps money circulating locally, creates quality jobs, builds household assets, and gives residents economic control. Community wealth building contrasts with extractive development that profits outside investors.",
        "category": "Community Development",
        "louisville_context": "Louisville's economy is dominated by corporations extracting profits to distant shareholders rather than locally-owned businesses building community wealth. West Louisville particularly lacks locally-owned businesses and community-controlled assets. Economic development incentives typically subsidize corporate expansions rather than community wealth building. This extractive model perpetuates poverty and economic powerlessness in low-income communities.",
        "why_it_matters": "When community wealth flows to outside shareholders, communities remain poor despite economic activity. Community wealth building keeps money local, creates better jobs (locally-owned businesses pay better than corporate chains), builds household assets through homeownership and ownership stakes, and gives residents economic power. Shifting from extractive to community wealth building transforms communities from colonies into economic actors.",
        "related_terms": "Economic Development, Worker Cooperatives, Community Land Trust, Local Ownership, Cooperative Economics",
        "dave_proposal": "Dave will redirect economic development investments toward community wealth building: supporting worker cooperative development, providing low-interest loans for locally-owned businesses, establishing community land trusts, supporting community development financial institutions, and prioritizing local ownership over corporate subsidies. Programs funded within $1.025 billion budget, focusing on West Louisville and underserved areas.",
        "aliases": "Local Wealth Building, Community Economics, Cooperative Economics, Asset Building"
    },
    {
        "term": "Worker Cooperative",
        "definition": "Businesses owned and democratically controlled by their workers, with each worker having one vote regardless of capital contribution. Worker cooperatives distribute profits among worker-owners rather than distant shareholders, creating quality jobs with ownership stakes. Cooperatives provide job security, workplace democracy, wealth building for working people, and community accountability. Worker cooperatives are powerful community wealth-building and economic justice tools.",
        "category": "Community Development",
        "louisville_context": "Louisville has very few worker cooperatives despite their success in other cities. Most Louisville workers are employed by corporations extracting profits to shareholders rather than building worker wealth. Low-income communities particularly lack cooperative businesses that could provide quality jobs with ownership opportunities. Limited technical assistance and startup capital for cooperative development constrains growth despite worker interest.",
        "why_it_matters": "Traditional employment extracts value from workers' labor to enrich distant shareholders. Worker cooperatives enable working people to own their workplaces, share profits, make democratic decisions, and build assets. Cooperatives provide quality jobs that can't be eliminated by distant corporate decisions. In communities experiencing economic extraction, cooperatives build community wealth and economic self-determination.",
        "related_terms": "Community Wealth Building, Employee Ownership, Cooperative Economics, Economic Democracy, Worker Ownership",
        "dave_proposal": "Dave will launch Louisville Worker Cooperative Initiative (funded within $1.025 billion budget) providing technical assistance, startup capital, and ongoing support for cooperative development. Priority support for cooperatives in West Louisville and other underserved areas. Community Wellness Centers will host cooperative education and development assistance. Dave will direct Metro procurement to prioritize worker-owned businesses, creating demand supporting cooperative growth.",
        "aliases": "Worker-Owned Business, Cooperative Business, Employee-Owned Cooperative, Worker Ownership"
    },
    {
        "term": "Social Enterprise",
        "definition": "Businesses organized to achieve social missions (reducing poverty, employing people with barriers, environmental protection) while generating revenue through selling goods or services. Social enterprises balance mission and money, using business methods for social purposes. Examples include businesses employing formerly incarcerated people, providing transitional jobs for people experiencing homelessness, or offering living wage jobs in disinvested neighborhoods. Social enterprises fill gaps that neither pure charity nor traditional business addresses.",
        "category": "Community Development",
        "louisville_context": "Louisville has several successful social enterprises including Goodwill Industries (employing people with barriers), Chrysalis House's enterprises (supporting women in recovery), and smaller mission-driven businesses. However, Louisville could support far more social enterprises addressing employment barriers, poverty, and community needs. Limited access to patient capital (investors accepting lower returns for mission) and technical assistance constrains social enterprise development.",
        "why_it_matters": "Traditional businesses prioritize profit over mission while nonprofits depend on donations. Social enterprises combine business sustainability with social mission, creating jobs for people excluded from mainstream employment, generating revenue for mission, and building community wealth. Social enterprises provide pathways to employment for people with criminal records, recovery challenges, or other barriers conventional employers exclude.",
        "related_terms": "Community Wealth Building, Employment Barriers, Workforce Development, Inclusive Economy, Mission-Driven Business",
        "dave_proposal": "Dave will support social enterprise development through Metro procurement prioritizing social enterprises (within $1.025 billion budget), low-interest loans for social enterprise startups, technical assistance for mission-driven businesses, and partnerships between Community Wellness Centers and social enterprises creating employment pathways. Priority support for enterprises employing people with criminal records, people in recovery, and other excluded populations.",
        "aliases": "Mission-Driven Business, Purpose-Driven Enterprise, Social Purpose Business"
    },
    {
        "term": "Community Engagement",
        "definition": "Meaningful involvement of community members in government decisions affecting their neighborhoods—going beyond information-sharing to genuine collaboration and shared power. Authentic community engagement includes early involvement (before decisions are made), accessible processes (convenient times/locations, childcare, interpretation), compensation for residents' time, incorporating community input into final decisions, and transparency about how input influenced outcomes. Tokenistic engagement checks boxes without transferring real power.",
        "category": "Community Development",
        "louisville_context": "Louisville Metro Government often conducts superficial community engagement: single evening meetings in inconvenient locations without childcare, presenting already-made decisions for comment rather than genuine collaboration, and ignoring community input that conflicts with predetermined plans. Low-income communities and communities of color particularly experience tokenistic engagement where their input is solicited but not meaningfully considered. Residents grow cynical when 'engagement' becomes rubber-stamping predetermined decisions.",
        "why_it_matters": "Decisions made without meaningful community input often fail, create unintended harms, or perpetuate inequality. Communities know their needs better than outside experts. Authentic engagement produces better decisions, builds community capacity, increases resident ownership of outcomes, and demonstrates respect. Tokenistic engagement wastes residents' time, breeds cynicism, and perpetuates power imbalances.",
        "related_terms": "Community Development, Community Organizing, Participatory Democracy, Resident Leadership, Public Participation",
        "dave_proposal": "Dave will transform Metro Government's community engagement through mandatory standards: early engagement before key decisions, multiple accessible meetings with childcare and interpretation, compensating residents for participation, demonstrating how input shaped decisions, and community veto power for decisions fundamentally affecting neighborhoods. Community Wellness Centers will host engagement processes. All significant Metro decisions will undergo genuine community engagement.",
        "aliases": "Public Engagement, Civic Engagement, Community Participation, Resident Input"
    },
    {
        "term": "Participatory Budgeting",
        "definition": "A democratic process where community members directly decide how to spend part of a public budget through proposal development, deliberation, and voting. Participatory budgeting (PB) gives residents real power over government spending, builds civic engagement, addresses community priorities, and increases budget transparency. PB typically focuses on capital improvements (parks, streets, facilities) ranging from $100,000 to several million. PB has spread worldwide since pioneering in Porto Alegre, Brazil.",
        "category": "Community Development",
        "louisville_context": "Louisville has never implemented participatory budgeting despite its success in peer cities including Chicago, New York, and many others. Metro Council members have full discretion over their district budgets with minimal community input. This allows political considerations rather than community needs to drive spending decisions. PB could transform capital improvement decisions from political favors to community priorities while building civic engagement.",
        "why_it_matters": "Participatory budgeting democratizes government spending, ensures resources address genuine community needs rather than political priorities, builds civic knowledge and engagement, and demonstrates government accountability. PB participants gain understanding of budget constraints and government operations while government gains insight into community priorities. PB is democracy in action—residents directly controlling public resources.",
        "related_terms": "Community Engagement, Budget Process, Democratic Participation, Community Development, Civic Engagement",
        "dave_proposal": "Dave will implement participatory budgeting in his first term, allocating $5 million annually (within $1.025 billion budget) for residents to directly decide capital improvements in their neighborhoods. Community Wellness Centers will host PB processes. Process will include idea collection, proposal development, community voting, and implementation with ongoing transparency. PB will expand based on success, potentially reaching $20+ million annually.",
        "aliases": "PB, Community Budgeting, Democratic Budgeting, Citizen Budgeting"
    },
    {
        "term": "Digital Equity",
        "definition": "Ensuring all residents have access to affordable internet, devices, and digital skills necessary for full participation in modern society. Digital equity addresses the digital divide through subsidized internet service, device lending/distribution, digital literacy training, and tech support. Digital equity recognizes that internet access is essential for education, employment, healthcare, government services, and civic participation—not a luxury.",
        "category": "Technology & Community Development",
        "louisville_context": "Approximately 30,000 Louisville households (15%) lack home internet, concentrated in low-income neighborhoods. During COVID-19 remote learning, thousands of JCPS students couldn't access online education. Many low-income adults can't search for jobs, access telehealth, or complete government applications online. Libraries provide internet access but have limited hours and locations. Internet service costs $50-100 monthly—unaffordable for many families.",
        "why_it_matters": "The digital divide perpetuates and widens inequality. Students without internet can't complete homework; job seekers can't apply online; patients can't access telehealth; residents can't access government services increasingly moving online. Digital inequity excludes people from education, employment, healthcare, and civic participation—creating compounding disadvantages.",
        "related_terms": "Digital Divide, Broadband Access, Educational Equity, Internet Access, Technology Access",
        "dave_proposal": "Dave will expand digital equity through public Wi-Fi at Community Wellness Centers, libraries, and parks; device lending programs providing laptops/tablets; digital literacy classes for all ages; and partnerships with internet providers offering low-cost service ($10-20/month) for low-income households. Programs funded within $1.025 billion budget, ensuring every Louisville resident has internet access within walking distance.",
        "aliases": "Digital Inclusion, Technology Equity, Internet Equity, Connectivity Equity"
    },
    {
        "term": "Civic Engagement",
        "definition": "Active participation in community and government through voting, attending meetings, volunteering, organizing, advocacy, and working to improve communities. Civic engagement strengthens democracy, holds government accountable, builds community connections, and empowers residents to shape their communities' futures. Barriers to civic engagement include lack of time, information, childcare, transportation, language access, and feeling that participation doesn't matter.",
        "category": "Community Development",
        "louisville_context": "Louisville has low civic engagement, particularly in low-income communities: voter turnout below 30% in local elections, public meetings poorly attended, many residents unaware of government decisions affecting them. Barriers include inconvenient meeting times/locations, lack of childcare, limited language access, complex government processes, and cynicism from past experiences where input was ignored. Low engagement allows government to function without accountability to affected communities.",
        "why_it_matters": "Democracy requires informed, engaged citizens holding government accountable. When low-income communities and communities of color have low civic engagement, their needs become politically invisible, allowing government to ignore them. Increasing engagement requires removing barriers (childcare, interpretation, accessible processes) and demonstrating that participation matters through responsive government.",
        "related_terms": "Community Engagement, Voter Participation, Civic Participation, Democratic Engagement, Community Organizing",
        "dave_proposal": "Dave will increase civic engagement through Community Wellness Centers serving as civic hubs, hosting accessible community meetings with childcare and interpretation, providing civic education, supporting voter registration and turnout, and demonstrating responsive government that acts on community input. He'll ensure all Metro meetings offer childcare, interpretation, and evening/weekend options expanding access.",
        "aliases": "Civic Participation, Community Participation, Democratic Engagement, Public Engagement"
    },
    {
        "term": "Community Resilience",
        "definition": "Communities' ability to withstand and recover from shocks (disasters, economic downturns, public health crises) through strong social networks, diverse economies, quality infrastructure, and adaptive capacity. Resilient communities have resources and relationships enabling mutual aid during crises, economic diversity preventing total collapse from single industry loss, infrastructure withstanding disasters, and capacity to adapt to changing conditions. Building resilience requires long-term investment in community bonds and systems.",
        "category": "Community Development",
        "louisville_context": "Louisville's resilience varies dramatically by neighborhood. East End neighborhoods have strong social capital, economic resources, and quality infrastructure enabling recovery from shocks. West Louisville neighborhoods have weaker resilience: limited economic resources, deteriorating infrastructure, and social capital strained by disinvestment and poverty. COVID-19 revealed resilience gaps—low-income communities suffered disproportionate health and economic impacts with less capacity to withstand extended crisis.",
        "why_it_matters": "Climate change, economic volatility, and other challenges will bring increasing shocks. Communities lacking resilience experience catastrophic impacts from crises while resilient communities weather storms. Building West Louisville's resilience requires strengthening social networks, diversifying economic opportunities, improving infrastructure, and ensuring resources for crisis response. Resilience building is essential preparation for inevitable future challenges.",
        "related_terms": "Community Development, Social Capital, Disaster Preparedness, Community Wellness, Mutual Aid",
        "dave_proposal": "Dave's Community Wellness Centers build community resilience through strong social networks, crisis response capacity (food, supplies, cooling/heating centers), health services preventing crisis escalation, economic support, and community organizing. His $1.025 billion budget prioritizes infrastructure improvements in vulnerable neighborhoods. He'll establish neighborhood-based resilience planning ensuring all communities can withstand and recover from shocks.",
        "aliases": "Community Strength, Neighborhood Resilience, Crisis Resilience, Adaptive Capacity"
    },
    {
        "term": "Social Capital",
        "definition": "The networks, relationships, and trust among community members that enable collective action, mutual support, and cooperation. Strong social capital means neighbors know and help each other, community organizations coordinate effectively, residents trust each other and institutions, and collective action addresses shared problems. Social capital predicts community health, safety, economic outcomes, and resilience. Poverty and disinvestment erode social capital.",
        "category": "Community Development",
        "louisville_context": "Louisville neighborhoods have vastly different social capital levels. Affluent neighborhoods have strong networks through schools, churches, civic organizations, and shared spaces enabling collective action. Many West Louisville neighborhoods have eroded social capital from decades of disinvestment, population loss, poverty stress, and lack of community gathering spaces. Low social capital limits collective problem-solving and community power.",
        "why_it_matters": "Social capital enables communities to solve problems collectively, support vulnerable members, resist harmful external forces, and advocate effectively for needs. Neighborhoods lacking social capital struggle even when resources increase—without strong relationships and trust, neighbors can't organize effectively. Building social capital requires spaces for gathering, opportunities for cooperation, and reducing stressors (poverty, crime) that undermine trust.",
        "related_terms": "Community Development, Community Resilience, Community Organizing, Social Networks, Community Cohesion",
        "dave_proposal": "Dave's Community Wellness Centers build social capital through gathering spaces, programs bringing neighbors together, community events, support groups, and organizing opportunities. His increased Metro Parks budget ($8 million annually within $1.025 billion total) expands programming creating social connections. All Metro policies will be evaluated for social capital impacts—does it strengthen or weaken community bonds?",
        "aliases": "Community Networks, Social Networks, Community Bonds, Neighborhood Connections"
    },
    {
        "term": "Cultural Competence",
        "definition": "The ability of individuals and organizations to effectively interact with people from diverse cultural backgrounds, recognizing cultural differences, avoiding assumptions, adapting communication and services, and providing culturally appropriate services. Cultural competence requires self-awareness about one's own culture, knowledge about other cultures, skills for cross-cultural interaction, and organizational systems supporting cultural responsiveness. Culturally incompetent services alienate and harm communities they're meant to serve.",
        "category": "Community Development",
        "louisville_context": "Louisville Metro Government and many service providers lack cultural competence, particularly serving Black residents, immigrants, and refugees. Services designed without cultural understanding fail to reach intended communities or cause unintended harms. Limited language access excludes non-English speakers. Implicit bias affects service delivery. Staffing doesn't reflect community diversity. Cultural incompetence wastes resources on ineffective services while alienating communities.",
        "why_it_matters": "Culturally incompetent services fail. When government and service providers don't understand communities they serve, services don't address real needs, communication fails, and trust is impossible. Cultural competence isn't political correctness—it's effectiveness. Services designed with cultural competence reach intended communities, build trust, and achieve better outcomes than one-size-fits-all approaches.",
        "related_terms": "Diversity, Equity, Inclusion, Community Engagement, Service Delivery",
        "dave_proposal": "Dave will require cultural competence training for all Metro Government employees, ensure staff diversity reflects community demographics, provide language access at all service points, involve community members in service design, and establish Community Wellness Centers governed by residents ensuring cultural responsiveness. He'll measure cultural competence through community feedback and outcomes, funded within $1.025 billion budget.",
        "aliases": "Cultural Responsiveness, Cultural Awareness, Cross-Cultural Competence, Cultural Humility"
    }
]

# Output JSON file
output_file = '/home/dave/skippy/claude/downloads/extracted/glossary_expansion_part5_final.json'

with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(new_terms, f, indent=2, ensure_ascii=False)

print(f"Generated {len(new_terms)} new terms in Part 5 (FINAL):")
print(f"  - Community Development: 18 terms")
print(f"\nSaved to: {output_file}")
print(f"\nTotal new terms in Part 5: {len(new_terms)}")
print("\n🎯 This is the FINAL expansion to push us over 350 total terms!")
