#!/bin/bash
# =============================================================================
# Crypto Portfolio Deployment Script for Ebon Server
# Version: 1.0.0
# Created: 2026-02-02
#
# Runs from dave's local machine, SSHes to ebon for all operations.
#
# Prerequisites (manual SSH to ebon required):
#   sudo apt-get update && sudo apt-get install -y docker-compose-plugin
#   git config --global user.name "Ebon Server"
#   git config --global user.email "ebon@local"
#
# Usage:
#   ./deploy_to_ebon.sh [init|update|start|stop|restart|status|logs|monitor]
# =============================================================================

set -euo pipefail

EBON_HOST="ebon"
REPO_URL="https://github.com/eboncorp/skippy-system-manager.git"
REPO_DIR="/home/ebon/skippy-system-manager"
APP_DIR="$REPO_DIR/mcp-servers/crypto-portfolio"
SSH_OPTS="-o ConnectTimeout=10"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1"; }
header() { echo -e "\n${CYAN}=== $1 ===${NC}"; }

run_ebon() {
    ssh $SSH_OPTS "$EBON_HOST" "$1"
}

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------
check_ssh() {
    info "Checking SSH to ebon..."
    if ! run_ebon "echo ok" >/dev/null 2>&1; then
        err "Cannot SSH to ebon. Check connectivity and YubiKey."
        exit 1
    fi
    info "SSH OK"
}

check_compose() {
    info "Checking Docker Compose on ebon..."
    if ! run_ebon "docker compose version" >/dev/null 2>&1; then
        err "Docker Compose plugin not installed on ebon."
        echo ""
        echo "  Fix: SSH to ebon and run:"
        echo "    sudo apt-get update && sudo apt-get install -y docker-compose-plugin"
        echo ""
        exit 1
    fi
    info "Docker Compose OK"
}

preflight() {
    check_ssh
    check_compose
}

# ---------------------------------------------------------------------------
# init — first-time deployment
# ---------------------------------------------------------------------------
cmd_init() {
    header "Initial Deployment"
    preflight

    # Check if repo already exists
    if run_ebon "test -d '$REPO_DIR'" 2>/dev/null; then
        warn "Repository already exists at $REPO_DIR"
        read -rp "Delete and re-clone? (y/N): " confirm
        if [[ "${confirm,,}" == "y" ]]; then
            info "Removing existing repo..."
            run_ebon "rm -rf '$REPO_DIR'"
        else
            info "Skipping clone. Use 'update' to pull latest."
            cmd_build
            return
        fi
    fi

    # Clone
    info "Cloning repository..."
    run_ebon "git clone '$REPO_URL' '$REPO_DIR'"

    # Create credential placeholder dirs (prevents Docker bind mount errors)
    info "Creating credential placeholder directories..."
    run_ebon "mkdir -p /home/ebon/.config/coinbase /home/ebon/.config/kraken"

    # Generate .env
    if ! run_ebon "test -f '$APP_DIR/.env'" 2>/dev/null; then
        info "Generating .env with secure passwords..."
        PG_PASS=$(openssl rand -base64 32)
        GF_PASS=$(openssl rand -base64 24)

        ssh $SSH_OPTS "$EBON_HOST" "cat > '$APP_DIR/.env' && chmod 600 '$APP_DIR/.env'" <<EOF
# Generated by deploy_to_ebon.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
PAPER_TRADING=true
LOG_LEVEL=INFO
POSTGRES_PASSWORD=$PG_PASS
GRAFANA_PASSWORD=$GF_PASS

# Agent runner
AGENT_MODE=paper
AGENT_LOG_DIR=/app/data/agent_logs

# Exchange API keys (empty = paper trading only)
COINBASE_API_KEY=
COINBASE_API_SECRET=
KRAKEN_API_KEY=
KRAKEN_API_SECRET=
CRYPTO_COM_API_KEY=
CRYPTO_COM_API_SECRET=
GEMINI_API_KEY=
GEMINI_API_SECRET=
ETH_WALLET_1=

# Notifications (optional)
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
NOTIFICATION_EMAIL=
EOF
        info "Created .env (chmod 600)"
    else
        warn ".env already exists, skipping"
    fi

    cmd_build
    echo ""
    info "Init complete. Next: ./deploy_to_ebon.sh start"
}

# ---------------------------------------------------------------------------
# build — build Docker images
# ---------------------------------------------------------------------------
cmd_build() {
    header "Building Docker Images"
    info "This may take several minutes on first run..."
    run_ebon "cd '$APP_DIR' && docker compose build"
    info "Build complete"
}

# ---------------------------------------------------------------------------
# update — git pull + rebuild
# ---------------------------------------------------------------------------
cmd_update() {
    header "Updating Deployment"
    preflight

    info "Pulling latest code..."
    run_ebon "cd '$REPO_DIR' && git pull"

    cmd_build
    echo ""
    info "Update complete. Run './deploy_to_ebon.sh restart' to apply."
}

# ---------------------------------------------------------------------------
# start — start core services
# ---------------------------------------------------------------------------
cmd_start() {
    header "Starting Services (Paper Mode)"
    preflight

    run_ebon "cd '$APP_DIR' && docker compose up -d"

    info "Waiting for healthchecks..."
    sleep 15
    cmd_status
}

# ---------------------------------------------------------------------------
# monitor — start with prometheus + grafana
# ---------------------------------------------------------------------------
cmd_monitor() {
    header "Starting Services + Monitoring"
    preflight

    run_ebon "cd '$APP_DIR' && docker compose --profile monitoring up -d"

    info "Waiting for healthchecks..."
    sleep 15
    cmd_status
    echo ""
    info "Grafana: http://10.0.0.29:3000 (admin / see GRAFANA_PASSWORD in .env)"
    info "Prometheus: http://10.0.0.29:9090"
}

# ---------------------------------------------------------------------------
# stop — stop all services
# ---------------------------------------------------------------------------
cmd_stop() {
    header "Stopping Services"
    check_ssh
    run_ebon "cd '$APP_DIR' && docker compose --profile monitoring down"
    info "All services stopped"
}

# ---------------------------------------------------------------------------
# restart — restart services
# ---------------------------------------------------------------------------
cmd_restart() {
    header "Restarting Services"
    check_ssh
    run_ebon "cd '$APP_DIR' && docker compose restart"
    sleep 10
    cmd_status
}

# ---------------------------------------------------------------------------
# status — health checks
# ---------------------------------------------------------------------------
cmd_status() {
    header "Service Status"
    check_ssh

    run_ebon "cd '$APP_DIR' && docker compose ps"

    echo ""
    header "Health Checks"

    # MCP Server
    if run_ebon "curl -sf http://localhost:8080/health" >/dev/null 2>&1; then
        info "MCP Server .... healthy"
    else
        err  "MCP Server .... not responding"
    fi

    # PostgreSQL
    if run_ebon "cd '$APP_DIR' && docker compose exec -T postgres pg_isready -U crypto -d crypto_portfolio" >/dev/null 2>&1; then
        info "PostgreSQL .... ready"
    else
        err  "PostgreSQL .... not ready"
    fi

    # Redis
    if run_ebon "cd '$APP_DIR' && docker compose exec -T redis redis-cli ping" 2>/dev/null | grep -q PONG; then
        info "Redis ......... connected"
    else
        err  "Redis ......... not responding"
    fi

    # Agent runner (check if container is running)
    if run_ebon "docker ps --filter name=crypto-portfolio-agents --format '{{.Status}}'" 2>/dev/null | grep -q Up; then
        info "Agent Runner .. running"
    else
        err  "Agent Runner .. not running"
    fi

    # Worker
    if run_ebon "docker ps --filter name=crypto-portfolio-worker --format '{{.Status}}'" 2>/dev/null | grep -q Up; then
        info "Worker ........ running"
    else
        err  "Worker ........ not running"
    fi
}

# ---------------------------------------------------------------------------
# logs — tail service logs
# ---------------------------------------------------------------------------
cmd_logs() {
    check_ssh
    local svc="${1:-}"
    if [[ -n "$svc" ]]; then
        info "Logs for $svc (Ctrl+C to exit)..."
        run_ebon "cd '$APP_DIR' && docker compose logs -f --tail=100 $svc"
    else
        info "All logs (Ctrl+C to exit)..."
        run_ebon "cd '$APP_DIR' && docker compose logs -f --tail=50"
    fi
}

# ---------------------------------------------------------------------------
# help
# ---------------------------------------------------------------------------
cmd_help() {
    cat <<EOF
Crypto Portfolio Deployment — Ebon Server (10.0.0.29)

Usage: ./deploy_to_ebon.sh <command> [args]

Commands:
  init       First-time setup (clone, .env, build)
  update     Pull latest code and rebuild images
  build      Rebuild Docker images only
  start      Start core services (paper trading)
  monitor    Start with monitoring (prometheus + grafana)
  stop       Stop all services
  restart    Restart all services
  status     Show service status and health checks
  logs       Tail all logs (Ctrl+C to exit)
  logs <svc> Tail specific service (mcp-server, agent-runner, worker, postgres, redis)
  help       Show this message

Prerequisites:
  ssh ebon 'sudo apt-get install -y docker-compose-plugin'
  ssh ebon 'git config --global user.name "Ebon" && git config --global user.email "ebon@local"'

Endpoints (after start):
  MCP Server:  http://10.0.0.29:8080
  Grafana:     http://10.0.0.29:3000  (if monitoring)
  Prometheus:  http://10.0.0.29:9090  (if monitoring)
EOF
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
case "${1:-help}" in
    init)     cmd_init ;;
    update)   cmd_update ;;
    build)    cmd_build ;;
    start)    cmd_start ;;
    monitor)  cmd_monitor ;;
    stop)     cmd_stop ;;
    restart)  cmd_restart ;;
    status)   cmd_status ;;
    logs)     cmd_logs "${2:-}" ;;
    help|*)   cmd_help ;;
esac
